/**
 * Auto Generated and Deployed by Cirrus Files
 **/
@isTest
private class Cirrus_Files_ColoniaFraccionamientoTests {
    static testMethod void test_ColoniaFraccionamiento() {
        Test.startTest();
        sObject sobj = new ColoniaFraccionamiento__c();
        /* If necessary, set fields for ColoniaFraccionamiento__c validation rules **HERE** */
        sobj = IGD.CirrusFilesTests.CreateRecord(sobj);
        Test.stopTest();
    }
}