@isTest
private class TestSchedulerRemoverPromotor {
	
	@isTest
	static void test_method_one() {
		
		//Test.startTest();
		
		//Sorteo__c sorteo = new Sorteo__c();
		//sorteo.Fecha_de_inicio__c = System.today().addDays(-10);
		//sorteo.Fecha_de_fin__c = System.today().addDays(10);
		//sorteo.Name ='La casa de tus sueños';
		
		//insert sorteo;
		
		//	Profile perfilGerenteVentas = [SELECT Id FROM Profile WHERE Name = 'Gerente de Ventas' LIMIT 1];
			
		//	User u1 = new User();
		//	u1.Alias = 'standtst';
		//	u1.Email='standardusertst@testorg.com'; 
		//	u1.EmailEncodingKey='UTF-8';
		//	u1.LastName='Testing';
		//	u1.LanguageLocaleKey='en_US'; 
  //          u1.LocaleSidKey='en_US';
  //          u1.Plaza__c = 'Dif-Mex';
  //          u1.TimeZoneSidKey='America/Los_Angeles';
  //          u1.UserName='standardusertst@testorg.com';
  //          u1.ProfileId = perfilGerenteVentas.Id;
            
  //          insert u1;
            
  //          User u2 = new User();
		//	u2.Alias = 'standt3';
		//	u2.Email='standardusertst2@testorg.com'; 
		//	u2.EmailEncodingKey='UTF-8';
		//	u2.LastName='Testing2';
		//	u2.LanguageLocaleKey='en_US'; 
  //          u2.LocaleSidKey='en_US';
  //          u2.Plaza__c = 'Mexicali';
  //          u2.TimeZoneSidKey='America/Los_Angeles';
  //          u2.UserName='standardusertst2@testorg.com';
  //          u2.ProfileId = perfilGerenteVentas.Id;
            
            
            
  //          insert u2;
            
            
  //          List<User> lstU = new List<User>();
  //          lstU.add(u1);
  //          lstU.add(u2);
            
            
  //          Id devRecordTypeIdCliente  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();


			
		//	Account cliente = new Account();
		//	cliente.Name = 'Juan Loyola';
		//	cliente.RecordTypeId = devRecordTypeIdCliente;
		//	cliente.CLABE__c = '2321340012';
		//	cliente.Cuenta_bancaria__c = '0989797989898';
		//	cliente.Beneficiario__c = 'Rosalia';
		//	cliente.Banco__c ='Banamex';
		//	cliente.Plaza__c = 'Dif-Mex';
		//	cliente.OwnerId = u1.Id;
			
			
		//	insert cliente;
			
		//	u1.Plaza__c = 'Durango';
		//	u1.Cambio_de_plaza__c = true;
			
		//	update u1;
			
		//	u2.Plaza__c = 'Dif-Mex';
		//	u2.Cambio_de_plaza__c = true;
			
		//	update u2;
			
		//	SchedulerRemoverPromotor sh1 = new SchedulerRemoverPromotor();
		//	String sch = '0 0 23 * * ?'; 
		//	system.schedule('Test Territory Check', sch, sh1); 
			
		//	String query =  'SELECT Id,Name,Plaza__c FROM USER WHERE Cambio_de_plaza__c = true';
		//	BatchRemoverPromotor bc = new BatchRemoverPromotor(query);
		
		
		//bc.execute(null,lstU);
		//bc.Finish(null);
		
			
		//Test.stopTest();
		
	}

}