@isTest
private class TestPropiedadesController2 {
  
  @isTest
  static void test_method_one() {
      
     Propiedad__c propiedades1  = new Propiedad__c();
        propiedades1.Name = 'test';
        propiedades1.Plaza__c='Torreon';
        propiedades1.Publicada_en_redes__c=!false;
        insert propiedades1;
        
            Propiedad__c propiedades2 = new Propiedad__c();
        propiedades2.Name = 'test1';
        propiedades2.Plaza__c='Aguascalientes';
        propiedades2.Publicada_en_redes__c=!false;
        insert propiedades2;
            
            Propiedad__c propiedades3  = new Propiedad__c();
        propiedades3.Name = 'test2';
        propiedades3.Plaza__c='Celaya';
        propiedades3.Publicada_en_redes__c=!false;
        insert propiedades3;
        
            Propiedad__c propiedades4  = new Propiedad__c();
        propiedades4.Name = 'test4';
        propiedades4.Plaza__c='Colima';
        propiedades4.Publicada_en_redes__c=!false;
        insert propiedades4;
        
            Propiedad__c propiedades5  = new Propiedad__c();
        propiedades5.Name = 'test5';
        propiedades5.Plaza__c='Durango';
        propiedades5.Publicada_en_redes__c=!false;
        insert propiedades5;
        
            Propiedad__c propiedades6  = new Propiedad__c();
        propiedades6.Name = 'test6';
        propiedades6.Plaza__c='Monterrey';
        propiedades6.Publicada_en_redes__c=!false;
        insert propiedades6;
        
            Propiedad__c propiedades7  = new Propiedad__c();
        propiedades7.Name = 'test7';
        propiedades7.Plaza__c='Queretaro';
        propiedades7.Publicada_en_redes__c=!false;
        insert propiedades7;
        
            Propiedad__c propiedades8  = new Propiedad__c();
        propiedades8.Name = 'test8';
        propiedades8.Plaza__c='San Luis Potosi';
        propiedades8.Publicada_en_redes__c=!false;
        insert propiedades8;
        
            Propiedad__c propiedades9  = new Propiedad__c();
        propiedades9.Name = 'test9';
        propiedades9.Plaza__c='Hermosillo';
        propiedades9.Publicada_en_redes__c=!false;
        insert propiedades9;
        
            Propiedad__c propiedades10  = new Propiedad__c();
        propiedades10.Name = 'test10';
        propiedades10.Plaza__c='Nuevo Laredo';
        propiedades10.Publicada_en_redes__c=!false;
        insert propiedades10;
        
            Propiedad__c propiedades11  = new Propiedad__c();
        propiedades11.Name = 'test11';
        propiedades11.Plaza__c='Reynosa';
        propiedades11.Publicada_en_redes__c=!false;
        insert propiedades11;
        
            Propiedad__c propiedades12  = new Propiedad__c();
        propiedades12.Name = 'test12';
        propiedades12.Plaza__c='Distrito Federal';
        propiedades12.Publicada_en_redes__c=!false;
        insert propiedades12;
        
            Propiedad__c propiedades13  = new Propiedad__c();
        propiedades13.Name = 'test13';
        propiedades13.Plaza__c='Estado de Mexico';
        propiedades13.Publicada_en_redes__c=!false;
        insert propiedades13;
        
            Propiedad__c propiedades14  = new Propiedad__c();
        propiedades14.Name = 'test14';
        propiedades14.Plaza__c='Guadalajara';
        propiedades14.Publicada_en_redes__c=!false;
        insert propiedades14;
        
            Propiedad__c propiedades15  = new Propiedad__c();
        propiedades15.Name = 'test15';
        propiedades15.Plaza__c='Tlajomulco';
        propiedades15.Publicada_en_redes__c=!false;
        insert propiedades15;
        
            Propiedad__c propiedades16  = new Propiedad__c();
        propiedades16.Name = 'test16';
        propiedades16.Plaza__c='Tonala';
        propiedades16.Publicada_en_redes__c=!false;
        insert propiedades16;
        
            Propiedad__c propiedades17  = new Propiedad__c();
        propiedades17.Name = 'test17';
        propiedades17.Plaza__c='Tabasco';
        propiedades17.Publicada_en_redes__c=!false;
        insert propiedades17;
        
            Propiedad__c propiedades18  = new Propiedad__c();
        propiedades18.Name = 'test18';
        propiedades18.Plaza__c='Veracruz';
        propiedades18.Publicada_en_redes__c=!false;
        insert propiedades18;
        
        Propiedad__c propiedades19  = new Propiedad__c();
        propiedades19.Name = 'test19';
        propiedades19.Plaza__c='Ensenada';
        propiedades19.Publicada_en_redes__c=!false;
        insert propiedades19;
        
        Propiedad__c propiedades20  = new Propiedad__c();
        propiedades20.Name = 'test20';
        propiedades20.Plaza__c='Mexicali';
        propiedades20.Publicada_en_redes__c=!false;
        insert propiedades20;
        
        Propiedad__c propiedades21  = new Propiedad__c();
        propiedades21.Name = 'test21';
        propiedades21.Plaza__c='Cancun';
        propiedades21.Publicada_en_redes__c=!false;
        insert propiedades21;
        
        Propiedad__c propiedades22  = new Propiedad__c();
        propiedades22.Name = 'test22';
        propiedades22.Plaza__c='Los Cabos';
        propiedades22.Publicada_en_redes__c=!false;
        insert propiedades22;
        
        Propiedad__c propiedades23  = new Propiedad__c();
        propiedades23.Name = 'test23';
        propiedades23.Plaza__c='Morelia';
        propiedades23.Publicada_en_redes__c=!false;
        insert propiedades23;
        
        Propiedad__c propiedades24  = new Propiedad__c();
        propiedades24.Name = 'test24';
        propiedades24.Plaza__c='Tarimbaro';
        propiedades24.Publicada_en_redes__c=!false;
        insert propiedades24;
        
        Propiedad__c propiedades25  = new Propiedad__c();
        propiedades25.Name = 'test25';
        propiedades25.Plaza__c='Vallarta';
        propiedades25.Publicada_en_redes__c=!false;
        insert propiedades25;
        
        Propiedad__c propiedades26  = new Propiedad__c();
        propiedades26.Name = 'test26';
        propiedades26.Plaza__c='Ahome';
        propiedades26.Publicada_en_redes__c=!false;
        insert propiedades26;
        
        Propiedad__c propiedades27  = new Propiedad__c();
        propiedades27.Name = 'test27';
        propiedades27.Plaza__c='Chihuahua';
        propiedades27.Publicada_en_redes__c=!false;
        insert propiedades27;
        
        Propiedad__c propiedades28  = new Propiedad__c();
        propiedades28.Name = 'test28';
        propiedades28.Plaza__c='Ciudad Juarez';
        propiedades28.Publicada_en_redes__c=!false;
        insert propiedades28;
        
        Propiedad__c propiedades29  = new Propiedad__c();
        propiedades29.Name = 'test29';
        propiedades29.Plaza__c='Culiacan';
        propiedades29.Publicada_en_redes__c=!false;
        insert propiedades29;
        
        Propiedad__c propiedades30  = new Propiedad__c();
        propiedades30.Name = 'test30';
        propiedades30.Plaza__c='Los Mochis';
        propiedades30.Publicada_en_redes__c=!false;
        insert propiedades30;
        
        Propiedad__c propiedades31  = new Propiedad__c();
        propiedades31.Name = 'test31';
        propiedades31.Plaza__c='Mazatlan';
        propiedades31.Publicada_en_redes__c=!false;
        insert propiedades31;
        
        Propiedad__c propiedades32  = new Propiedad__c();
        propiedades32.Name = 'test32';
        propiedades32.Plaza__c='Sinaloa';
        propiedades32.Publicada_en_redes__c=!false;
        insert propiedades32;
        
        Propiedad__c propiedades33  = new Propiedad__c();
        propiedades33.Name = 'test33';
        propiedades33.Plaza__c='Gomez Palacio';
        propiedades33.Publicada_en_redes__c=!false;
        insert propiedades33;
        
        Propiedad__c propiedades34  = new Propiedad__c();
        propiedades34.Name = 'test34';
        propiedades34.Plaza__c='Tijuana';
        propiedades34.Publicada_en_redes__c=!false;
        insert propiedades34;
       Test.startTest();
    
    PropiedadesController2 prop = new PropiedadesController2();
    List<Propiedad__c> pd = new List<Propiedad__c>();
    
    
    pd=prop.propiedades1;
    pd=prop.propiedades2;
    pd=prop.propiedades3;
    pd=prop.propiedades4;
    pd=prop.propiedades5;
    pd=prop.propiedades6;
    pd=prop.propiedades7;
    pd=prop.propiedades8;
    pd=prop.propiedades9;
    pd=prop.propiedades10;
    pd=prop.propiedades11;
    pd=prop.propiedades12;
    pd=prop.propiedades13;
    pd=prop.propiedades14;
    pd=prop.propiedades15;
    pd=prop.propiedades16;
    pd=prop.propiedades17;
    pd=prop.propiedades18;
    pd=prop.propiedades19;
    pd=prop.propiedades20;
    pd=prop.propiedades21;
    pd=prop.propiedades22;
    pd=prop.propiedades23;
    pd=prop.propiedades24;
    pd=prop.propiedades25;
    pd=prop.propiedades26;
    pd=prop.propiedades27;
    pd=prop.propiedades28;
    pd=prop.propiedades29;
    pd=prop.propiedades30;
    pd=prop.propiedades31;
    pd=prop.propiedades32;
    pd=prop.propiedades33;
    pd=prop.propiedades34;
    
    
    Integer pp1 = prop.countProp;
    Integer pp2 = prop.countProp2;
    Integer pp3 = prop.countPropAll;
    
    Map<String,String> mapaFotos = new Map<String,String>();
    mapaFotos=prop.mapaFotos1;
    mapaFotos=prop.mapaFotos2;
    mapaFotos=prop.mapaFotos3;
    mapaFotos=prop.mapaFotos4;
    mapaFotos=prop.mapaFotos5;
    mapaFotos=prop.mapaFotos6;
    mapaFotos=prop.mapaFotos7;
    mapaFotos=prop.mapaFotos8;
    mapaFotos=prop.mapaFotos9;
    mapaFotos=prop.mapaFotos10;
    mapaFotos=prop.mapaFotos11;
    mapaFotos=prop.mapaFotos12;
    mapaFotos=prop.mapaFotos13;
    mapaFotos=prop.mapaFotos14;
    mapaFotos=prop.mapaFotos15;
    mapaFotos=prop.mapaFotos16;
    mapaFotos=prop.mapaFotos17;
    mapaFotos=prop.mapaFotos18;
    mapaFotos=prop.mapaFotos19;
    mapaFotos=prop.mapaFotos20;
    mapaFotos=prop.mapaFotos21;
    mapaFotos=prop.mapaFotos22;
    mapaFotos=prop.mapaFotos23;
    mapaFotos=prop.mapaFotos24;
    mapaFotos=prop.mapaFotos25;
    mapaFotos=prop.mapaFotos26;
    mapaFotos=prop.mapaFotos27;
    mapaFotos=prop.mapaFotos28;
    mapaFotos=prop.mapaFotos29;
    mapaFotos=prop.mapaFotos30;
    mapaFotos=prop.mapaFotos31;
    mapaFotos=prop.mapaFotos32;
    mapaFotos=prop.mapaFotos33;
    mapaFotos=prop.mapaFotos34;
    
                       
    
    
    
    Test.stopTest();
    }
    }