@isTest
 
   private class TestPrueba_Consola_Stock_Controller{
       
       
       @isTest
  static void test_method_two() {
      Oferta__c stock = new Oferta__c();
       PageReference pagina = Page.Prueba_Consola_Stock;
      Test.setCurrentPage(pagina);
      Prueba_Consola_Stock_Controller controller = new Prueba_Consola_Stock_Controller();
      Prueba_Consola_Stock_Controller ctrdesa = new Prueba_Consola_Stock_Controller();
      Prueba_Consola_Stock_Controller glorep = new Prueba_Consola_Stock_Controller();
      Prueba_Consola_Stock_Controller campos = new Prueba_Consola_Stock_Controller();
      Prueba_Consola_Stock_Controller condiciones = new Prueba_Consola_Stock_Controller();
      Prueba_Consola_Stock_Controller glorep2 = new Prueba_Consola_Stock_Controller();
      ctrdesa.cobertura();
      
      
       
  }
       
 
 }